// ==UserScript==
// @name V2AJAX (Ajax Submit in V2EX)
// @description using ajax to submit in v2ex.
// @version 0.2
// @auther yyfearth@gmail.com
// @include *://*.v2ex.com/t/*
// @match *://*.v2ex.com/t/*
// ==/UserScript==
(function(){var a=null,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p=[].slice;d=function(b,c){return c==a&&(c=document),c.querySelector(b)},e=function(b,c){return c==a&&(c=document),[].slice.call(c.querySelectorAll(b))},c=function(a,b,c){a.addEventListener(b,c,!1)},b=function(b){var c,d,e,f,g,h,i,j,k;k=b!=a?b:{},j=k.c,f=k.method,i=k.url,d=k.data,b=k.async,h=k.timeout,c=k.complete,g=k.a,e=k.error,j==a&&(j=new XMLHttpRequest),b==a&&(b=!0),j.open(f,i,b),/^post$/i.test(f)&&j.setRequestHeader("Content-type","application/x-www-form-urlencoded"),h&&(j.timeout=h),j.onreadystatechange=function(){if(j.readyState===4)return typeof c=="function"&&c(j),j.status===200?typeof g=="function"?g(j.responseText,j):void 0:typeof e=="function"?e(j.status,j.responseText,j):void 0},j.ontimeout=function(){return typeof e=="function"?e(j.status,"timeout",j):void 0},j.send(d)},g=function(){var b,c;b=arguments[0],c=2<=arguments.length?p.call(arguments,1):[],b==a&&(b=!0),console.error.apply(console,c),"submit"===b?n.submit():"reload"===b?location.reload():console.log("failed",b)},h=function(b){var c;return b==a&&(b=document),c=/\u611f\u8c22\u56de\u590d\u8005|\u76ee\u524d\u5c1a\u65e0\u56de\u590d|\d+\s*\u56de\u590d\s*\|\s*\u76f4\u5230/,(b=e("#Main>.box",b)[1])&&c.test(b.innerText||b.textContent)?b:a},m=d("#reply_content");for(n=m.parentElement;"FORM"!==n.tagName;)if(n=n.parentElement,!n)return g("stop","cannot find submit form");o=d('input[type="submit"]'),o.text=o.value,l=h(a);if(!h)return g("stop","cannot find replies box");i=function(a){o.classList[a?"remove":"add"]("normal"),o.disabled=!!a},j=function(a){var b,c;return a?(c="...",a="remove",b=!0):(c="",a="add",b=!1),o.value=o.text+c,o.classList[a]("normal"),o.disabled=m.disabled=b},k=function(a){var b;console.log("onsuccess",a),(a=a.trim())||(alert("ajax return empty result"),g("reload","empty return html")),a=a.replace(/<script.*?<\/script>/ig,""),b=document.createElement("doc"),b.innerHTML=a,(a=h(b))||g("reload","cannot locate new replies"),l.className=a.className,l.innerHTML=a.innerHTML,m.value="",m.focus()},o.type="button",o.onclick=f=function(){var a;console.log("ajax submit"),(a=m.value.trim())?(a="content="+encodeURIComponent(a),j(!0),b({url:n.action,method:n.method,data:a,timeout:5e3,a:k,error:function(a,b){return g("submit","ajax failed",a,b)},complete:function(){return j(!1)}})):i(!0)},c(m,"keydown",function(a){if((a.ctrlKey||a.metaKey)&&13===a.which)return a.preventDefault(),a.stopPropagation(),f(),!1}),c(m,"blur",function(){m.value=m.value.trim()}),(d=function(){var a;a=!m.value.trim(),m.b!==a&&i(a)})(),c(m,"input",d),o.insertAdjacentHTML("afterend",'<span class="fade"> '+(/Mac OS/i.test(navigator.userAgent)?"^/\u2318 + \u21b5":"ctrl+enter")+" </span>")})()
